repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src/makeup/
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        always_run: true
        pass_filenames: false
